#!/bin/bash
valor=$(cut -d":" -f3 /etc/passwd)
var=$(cut -d":" -f1 /etc/passwd)
numero_user=1
for i in $valor
do
        if [[ $i -lt 1000 || $i -gt 1999 ]]
        then
          numero_user=$((numero_user + 1))
        fi
 
done
echo $numero_user
